"""Compatibility facade for the shared engine and Full FT strategy."""

from pubmedqa.training.engine import (
    DEFAULT_ATTN_IMPLEMENTATION,
    DEFAULT_CHECKPOINT_PERCENTS,
    DEFAULT_CONDITION,
    DEFAULT_CPU_THREADS,
    DEFAULT_DATA_FRACTION,
    DEFAULT_DATA_REGIME,
    DEFAULT_DISTRIBUTED_MODE,
    DEFAULT_DEVICE,
    DEFAULT_DTYPE,
    DEFAULT_EVAL_BATCH_SIZE,
    DEFAULT_FSDP_CPU_OFFLOAD,
    DEFAULT_GRAD_ACCUM_STEPS,
    DEFAULT_LAYER_SCOPE,
    DEFAULT_LEARNING_RATE,
    DEFAULT_LOG_EVERY_STEPS,
    DEFAULT_MAX_GRAD_NORM,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_METHOD_NAME,
    DEFAULT_MODEL_NAME,
    DEFAULT_NOTES,
    DEFAULT_NUM_EPOCHS,
    DEFAULT_NUM_WORKERS,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_RUN_TAG,
    DEFAULT_SAVE_OPTIMIZER_STATE,
    DEFAULT_SEED,
    DEFAULT_TRAIN_BATCH_SIZE,
    DEFAULT_WARMUP_RATIO,
    DEFAULT_WEIGHT_DECAY,
    CheckpointRecord,
    EvalMetrics,
    EvalPrediction,
    EvalResult,
    FullFineTuneCliConfig,
    FullFineTuneConfig,
    LayerwiseReference,
    LayerwiseUpdateRecord,
    PubMedQAFullFineTuner,
    PubMedQASupervisedDataset,
    SupervisedDataCollator,
    SupervisedExample,
    TrainingSummary,
    TrainStepLog,
    _build_checkpoint_schedule,
    _cosine_similarity,
    _longest_common_prefix_length,
    _match_tracked_module,
    _normalize_checkpoint_percents,
    _parse_layer_index,
    main,
)

__all__ = [
    "FullFineTuneCliConfig",
    "FullFineTuneConfig",
    "PubMedQAFullFineTuner",
    "PubMedQASupervisedDataset",
    "SupervisedDataCollator",
    "SupervisedExample",
    "TrainingSummary",
    "main",
]


if __name__ == "__main__":
    main()
